### ISSUE TITLE
Integration into atom-community builds

### ISSUE THREAD

**Issue by aminya** [bus-stop/x-terminal#108]
As you already know, atom-ide-community plans to release community builds of atom. X-terminal is one of the first packages, we would like to include in our builds.

Here is the respective task in atom-ide-community projects:
https://github.com/atom-ide-community/atom/projects/4#card-41190368

I made this issue to track the x-terminal integration and any related task that we might need to do before integration such as determining the build process, etc. Once we integrated it into the build, we will close this. 

@UziTech You are already a member of the organization. Feel free to give me suggestions/pull requests. Thanks! 

P.S: there is no need to rename/transfer this repository! Let me know if you prefer to transfer this issue to the atom-ide-community repository instead.

**Comment by UziTech** [comment]
It would be great to have a built in terminal. What do you need us to do to help with that?

**Comment by aminya** [comment]
Something that I have not decided yet is that how we want to bundle the community packages. Should we build them with electron-link and put them in the asar archive or we want to install them inside the packages folder (keeps them upgradable).

Since X-terminal has a lot of dependencies, I wonder if electron-link will be able to bundle everything. For sure we can try! If we decide to burn x-terminal into electron-link, it would be better to use rollup to bundle everything. I successfully bundled a terminal like package before https://github.com/aminya/atom-ink/tree/rollup

**Comment by UziTech** [comment]
I would prefer all packages to be upgradable. I don't like how difficult it is to update or replace Atom's core packages.

A bundled terminal would be great but people should be able to replace or extend the core packages just as easily as any other package.

**Comment by UziTech** [comment]
The only difference between core packages and community packages should be that Atom comes with them by default.

**Comment by aminya** [comment]
I agree with that. However, not burning it into asar will not make a v8 snapshot for that package, unless there is another way for doing that. I think we should try rollup anyways since it greatly improves the performance.

**Comment by aminya** [comment]
Soon, I will make a pull request to build the x-terminal using rollup.

**Comment by aminya** [comment]
For your information, integrating X-terminal is set as the milestone of the first atomic atom.
https://github.com/atom-ide-community/atom/issues/91

**Comment by UziTech** [comment]
I wonder if it would be better to fork `x-terminal` and remove a bunch of the features to include a simpler terminal in atom-community.

When I forked `atom-xterm` to create `x-terminal` I tried to keep it as similar to `atom-xterm` so people would have an easier time moving to an updated version of xterm, but there are quite a few features I think I would change if I were to make the terminal from scratch.

For example remove profiles. The code to support profiles is ungodly complex, and probably a performance bottleneck. I would also remove/rename many of the settings. The `command` setting has confused quite a few people. And there should be a better way to set xterm terminal options than a JSON string.

Atom has a [terminal](https://atom.io/packages/terminal) package that was scrapped early, maybe we can take that package name from them and create it at https://github.com/atom-ide-community/terminal.

#109 and #126 would make more sense with a slimmed down integrated terminal.

**Comment by aminya** [comment]
That sounds reasonable. However, my concern is about the effort needed for doing this, and the more the code difference, it is harder to keep the two repositories in sync.

If you think some of the code is causing the performance issues, why not use lazy loading and only load the code if it is enabled in the config? Personally, I haven't used profiles.

You can make a major release, and apply all the changes you like! Don't force yourself to follow atom-xterm.

Regarding the profiles code, we should refactor that and make it an Atom feature instead! As I mentioned before, you should try to move most of the code to `settings-view` instead. Regarding profiles, I am planning on a project dependant configuration system for Atom. That means we can store configuration inside `.atom` folder. Other IDEs do similar things inside their project folders (e.g. `.idea`, `.vscode`, `.vs`, etc). Once we have that, the code for profiles can be simplified.

**Comment by UziTech** [comment]
> it is harder to keep the two repositories in sync.

I don't think we would need to keep them in sync. If I were to make all of the changes I want it would be pretty much a different package. The only similarity would be the way it interfaces with xterm.js and node-pty and the docks/panels.

> If you think some of the code is complex, why not use lazy loading and only load the code if it is enabled in the config?

I mean complex as in difficult to work with from a developer standpoint not a user.

> As I mentioned before, you should try to move most of the code to settings-view instead.

That is what I would do but again it would be a completely different package. I know a few people who use different profiles in x-terminal all the time so if we were to remove them from x-terminal they wouldn't be able to use it the same way.

I think some people would find profiles useful but I don't think the integrated terminal needs them.

**Comment by aminya** [comment]
> I don't think we would need to keep them in sync. If I were to make all of the changes I want it would be pretty much a different package. The only similarity would be the way it interfaces with xterm.js and node-pty and the docks/panels.

I can't promise to start and maintain a new package. If you are interested to do so, this can be a good idea.

> I know a few people who use different profiles in x-terminal all the time so if we were to remove them from x-terminal they wouldn't be able to use it the same way.
> 
> I think some people would find profiles useful but I don't think the integrated terminal needs them.

That's why major releases exist. If someone hardly depends on a feature, they should skip updating x-terminal. or instead, they move their configurations to the `.atom` based system.

For breaking changes, changing the name is not the only solution! Semver made major breaking releases just for this!

**Comment by UziTech** [comment]
> That's why major releases exist.

Major releases are essentially to warn users that something could have broken. If they stop updating x-terminal altogether than they don't get the benefit of future updates that might fix security or performance issues. Essentially making x-terminal an unmaintained package for them unless we backport patches to old major versions (which we don't).

**Comment by UziTech** [comment]
> If you are interested to do so, this can be a good idea.

I would be fine with maintaining it. I think it should be very simple so it wouldn't be difficult to make it feature complete. Then if they need more features they can install a package like x-terminal or one of the other terminal packages.

And make it extensible so additional packages would serve to add features to the integrated terminal.

**Comment by UziTech** [comment]
https://github.com/atom-ide-community/terminal has been created for this.
