### ISSUE TITLE
[BR] X-terminal does not change its dimensions by changing the panes dimension

### ISSUE THREAD

**Issue by aminya** [bus-stop/x-terminal#124]
- [] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [x] I have not tried uninstalling/reinstalling the terminal.
### Description
X-terminal does not change its dimensions by changing the panes dimension

### Steps to reproduce
1) Open a terminal and put in the bottom pane (besides) linter.
2) Resize so it's big.
3) type enter a couple of times so it gets filled.
4) now make the pane smaller 
5) x-terminal does not resize like how Windows terminal resizes
You can do this the other way around. Start with small and then make it bigger. The content does not go into the now empty black part.

**Expected behavior:**
Resizabliltiy like Windows terminal 

**Actual behavior:**

I expect my pointer to be the last line, and I should not have to scroll for seeing it.
![image](https://user-images.githubusercontent.com/16418197/88465253-2ed77380-ce87-11ea-90b9-eae954ac8afd.png)

**Reproduces how often:**
Always

### Versions

```
❯ atom -v

Atom    : 1.49.0       
Electron: 5.0.13       
Chrome  : 73.0.3683.121
Node    : 12.0.0       
```

```
❯ apm -v
apm  2.5.0
npm  6.14.5
node 10.20.1 x64    
atom 1.49.0
python 3.8.5        
git 2.27.0.windows.1
visual studio 2015  
```
OS name and version: Win 10
Terminal version: 8.2.3

**Comment by UziTech** [comment]
This is a known issue in xterm.js

**Comment by UziTech** [comment]
Maybe it changes based on the terminal but I think Powershell 7 works the way it is supposed to:

![x-terminal-scroll](https://user-images.githubusercontent.com/97994/88467408-79afb600-ce9c-11ea-9690-9044058461ac.gif)
![powershell-scroll](https://user-images.githubusercontent.com/97994/88467457-022e5680-ce9d-11ea-8204-658cfec5e5b9.gif)

**Comment by UziTech** [comment]
or are you referring to horizontal resizing?

it seems to work well for the current line:

![x-terminal-resize](https://user-images.githubusercontent.com/97994/88467616-4ff78e80-ce9e-11ea-8440-472178e6130f.gif)

but this is what I meant is a known issue in xterm. There are only a certain number of lines they re-render on resize:

![image](https://user-images.githubusercontent.com/97994/88467608-38200a80-ce9e-11ea-8403-34bdd510b0b0.png)

**Comment by UziTech** [comment]
I wouldn't really consider this a bug but just a limitation of the software.

**Comment by aminya** [comment]
I usually use the terminal either on the right side or on the bottom depending on the work. 

Yes, the side resizing does not work always.

The bottom resizing works sometimes, but not always. I can run clear once in a while to bring the cursor at the top. Maybe there is a command to bring it to the top without clearing (!?).  Like this: https://github.com/JunoLab/atom-ink/blob/e151e3d629bce5f0235505a91fdd1ed2895d0ca9/lib/console/console.js#L290

![x-terminal](https://user-images.githubusercontent.com/16418197/88483438-8c260000-cf2d-11ea-971e-3255646ba65d.gif)

**Comment by UziTech** [comment]
So your problem is that x-terminal doesn't move the text up when the cursor goes below the bottom of the screen?

Can you share your x-terminal configuration and your powershell configuration?

**Comment by aminya** [comment]
> So your problem is that x-terminal doesn't move the text up when the cursor goes below the bottom of the screen?
> 
> Can you share your x-terminal configuration and your powershell configuration?


Most of the things for x-terminal are on default
![image](https://user-images.githubusercontent.com/16418197/88490105-bba13080-cf5e-11ea-89b1-59da33ef09de.png)
![image](https://user-images.githubusercontent.com/16418197/88490101-b348f580-cf5e-11ea-9eb1-75c0e0949700.png)

For PowerShell I use a couple of fancy things like fonts or git status here and there, but those do not affect the terminal itself.

![image](https://user-images.githubusercontent.com/16418197/88490120-da9fc280-cf5e-11ea-8799-49eeb13474ff.png)
![image](https://user-images.githubusercontent.com/16418197/88490125-e12e3a00-cf5e-11ea-8d2a-b04ca43010a9.png)
![image](https://user-images.githubusercontent.com/16418197/88490129-ea1f0b80-cf5e-11ea-8c66-4aa4a6c3d3d0.png)
![image](https://user-images.githubusercontent.com/16418197/88490134-f5723700-cf5e-11ea-89e0-b79df49cf69b.png)

**Comment by UziTech** [comment]
do you have anything in "xterm.js Terminal Options" setting?

**Comment by aminya** [comment]
No. Everything is default:
![image](https://user-images.githubusercontent.com/16418197/88490340-9ad9da80-cf60-11ea-8f15-f4b3d3c5f05a.png)

**Comment by UziTech** [comment]
I think I figured out what is happening. We call `refitTerminal` whenever the terminal is resized but when dragging to a different dock x-terminal thought the terminal was hidden so it wouldn't refit.

In #129 I removed the observer after it is initially visible so it stops marking it as invisible.

If you could, try the code from that PR and see if it fixes your issue.
