### ISSUE TITLE
[Q] How do you automatically run a command? [Ubuntu 20.04 LTS]

### ISSUE THREAD

**Issue by vescgi** [bus-stop/x-terminal#131]
I would like to automatically execute a terminal command when booting it up from Atom.
I tried to do so by going to the x-terminal package and by changing the /bin/bash/ default command to  python3 script.py to automatically start my python file when opening the x-terminal but it didn't happen and instead it returned the error `xecvp(3) failed.: No such file or directory` also after I set the right directory in the directory options.
Anyways if I just set the right path and execute the command myself from the terminal it doesn't return any error.
Hope you can help me resolve this issue also if it's probably my fault and thanks for the patience.
Giuseppe.

![Screenshot from 2020-07-28 16-27-43](https://user-images.githubusercontent.com/68910536/88679227-8415be00-d0ef-11ea-8ef0-380700a1cace.png)
![Screenshot from 2020-07-28 16-28-43](https://user-images.githubusercontent.com/68910536/88679239-86781800-d0ef-11ea-97db-a9e6daa0e1c7.png)

**Comment by UziTech** [comment]
The `command` is which shell to load. It might work to do something like `bash -c "python3 script.py"`

**Comment by UziTech** [comment]
You could try a package like [terminal-commands](https://atom.io/packages/terminal-commands) to run a command when you dispatch a command from the command palette.

**Comment by vescgi** [comment]
Thanks for the answer, I was also wondering, is there any way to execute just whichever python file is already open or is that too much of a pain?

**Comment by UziTech** [comment]
That is something you could do easily with [terminal-commands](https://atom.io/packages/terminal-commands) but is beyond the scope of this package.

**Comment by vescgi** [comment]
could you please help me achieve that type of result, it's way out of my skill-set and it would mean a lot.

**Comment by UziTech** [comment]
These steps should work:

1. Install [x-terminal](https://atom.io/packages/x-terminal)
2. Install [terminal-commands](https://atom.io/packages/terminal-commands)
3. Open command palette (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>)
4. Run `Terminal Commands: Edit Config`
5. Copy this config
   ```json
   {
     "python3:execute": "python3 ${file}",
   }
   ```
6. Save file
7. Open python script
8. Open command palette
9. Run `Python3: Execute`

**Comment by vescgi** [comment]
really appreciate the help, only problem is it returns the following error. 
![python](https://user-images.githubusercontent.com/68910536/88727382-d545a200-d12f-11ea-9c8f-847eef399be1.png)

**Comment by UziTech** [comment]
Hmm can you provide your config.cson file?

**Comment by vescgi** [comment]
"*":
  "autocomplete-python":
    useKite: false
    useSnippets: "all"
  core:
    telemetryConsent: "no"
    themes: [
      "one-dark-ui"
      "atom-material-syntax"
    ]
  editor:
    fontFamily: "Sorurce Code Pro, "
    fontSize: 22
    scrollPastEnd: true
    tabLength: 4
  "exception-reporting":
    userId: "4e08dc75-732c-408c-8cc5-6861a4be796b"
  "hydrogen-python": {}
  "python-autopep8":
    formatOnSave: true
  "python-run-terminalnx":
    a_terminal_selection: "gnome-terminal"
  "terminal-commands": {}
  welcome:
    showOnStartup: false
  "x-terminal":
    spawnPtySettings:
      command: "Run Python3: Execute"
      cwd: "/home/httpeppe/python/projects/"
    terminalSettings: {}

**Comment by UziTech** [comment]
> command: "Run Python3: Execute"

The `command` setting should be the default

On my steps when I put "Run `Python3: Execute`" I meant from the command palette. You should be able to open the command palette by pressing the keys <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> and search for "Python3: Execute"

**Comment by UziTech** [comment]
You can read more about the command palette in [Atom docs](https://flight-manual.atom.io/getting-started/sections/atom-basics/#command-palette)

**Comment by UziTech** [comment]
You might also be able to reach more people to help with Atom on their [forum](https://discuss.atom.io/)

**Comment by vescgi** [comment]
I resolved the issue by switching terminal-x with termination
