### ISSUE TITLE
[BR] Ctrl-L is buggy

### ISSUE THREAD

**Issue by aminya** [bus-stop/x-terminal#137]
- [] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [x] I have not tried uninstalling/reinstalling the terminal.
### Description

CTRL+L does not work the same as running `clear` (pwsh). CTRL+L sometimes prints some extra strings or words.

CTRL+L:
![image](https://user-images.githubusercontent.com/16418197/89479428-6a602080-d758-11ea-828c-edad3f23557a.png)

clear:
![image](https://user-images.githubusercontent.com/16418197/89479410-63391280-d758-11ea-9e86-c555d003b8c6.png)

### Steps to reproduce
1. press CTRL+L
2.
3.

**Expected behavior:**
See above screenshots

**Actual behavior:**
See above screenshots

**Reproduces how often:**
Sometimes (not sure when)

### Versions
```
> atom --version

Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

```
> apm --version
❯ apm -v
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 3.8.5
git 2.28.0.windows.1
visual studio 2015
```
OS name and version: win 10 
Terminal version: 9.0.5

**Comment by UziTech** [comment]
If you are able to give me steps to reproduce it regularly I could try to help debug it but I have pressed <kbd>Ctrl</kbd> + <kbd>L</kbd> many times without ever having an issue.

**Comment by UziTech** [comment]
also <kbd>Ctrl</kbd> + <kbd>L</kbd> is not handled by x-terminal at all so this is probably something that will have to be fixed in xterm.js or node-pty

**Comment by aminya** [comment]
Sure. I'll try to give you more information once it happened again! I am going to search through xterm issues as well.

**Comment by UziTech** [comment]
If this is still an issue feel free to reopen and give more information about how to reproduce it.
