### ISSUE TITLE
[Q]  How to work with xterm.js Terminal Options?

### ISSUE THREAD

**Issue by the-j0k3r** [bus-stop/x-terminal#14]
### I would like to be able do the following

1. See https://github.com/xtermjs/xterm.js/blob/4.4.0/typings/xterm.d.ts#L38-L241
2. In enter `{ lineHeight: 20px, FontWeight: 600, cursorStyle: underline }`
3. Open a new terminal and compare to last.

Expecting things to change, tried various formats of options and no joy. So how do these work?

![generic](https://user-images.githubusercontent.com/31389848/75609170-a25a9c00-5b06-11ea-9d32-70d5452ffbf8.gif)

### Additional context

NA

**Comment by UziTech** [comment]
It has to be valid json so you will have to double quote the properties

```json
{ "lineHeight": "20px", "FontWeight": 600, "cursorStyle": "underline" }
```

**Comment by the-j0k3r** [comment]
Added https://github.com/bus-stop/x-terminal/commit/8c239162e6ea841cc8aca69eed12f2559c6f6d71 and https://github.com/bus-stop/x-terminal/commit/302fef107d19e53c396328fb39dcf1a0b1982adc

Users can now click the link and know what the syntax is. A better design would be to include an example in addition.

**Comment by UziTech** [comment]
> A better design would be to include an example in addition.

I like the link. I feel like the settings panel is not a good place for an example. Maybe in the readme.

**Comment by UziTech** [comment]
Alternatively we could use [json5](https://www.npmjs.com/package/json5) to parse the string so it could be any javascript object instead of strict JSON.

**Comment by the-j0k3r** [comment]
Its fine as is, its not worth trying to complicate this, 

It would be better to make it a call to action rather than just linkify, We can do that with a change of hows its worded.

Im not a fan of adding everything and the kitchen sink into the readme, in fact its way too long, most of them are,
