### ISSUE TITLE
Using normal atom key-bindings after doing stuff in x-terminal without touching the mouse?

### ISSUE THREAD

**Issue by softwarecreations** [bus-stop/x-terminal#140]
### I would like to be able do the following
1. Use my most common shortcut keys inside x-terminal in Linux
2. Alternatively press a key combo that causes x-terminal to lose focus so that my key-combo goes through to atom workspace (or whatever)

### Additional context
Often, after finishing some work I close all file tabs and complete my commits and PR in the terminal.
Then I'm ready to begin working on a new branch, but need to open some files.
None of the shortcut keys that I usually work while I'm in x-terminal.
The file tree-view is typically closed as well which means I was needing to use the mouse and menus (*yuck*)

But I've just discovered that I can click the statusbar below x-terminal and then my key-combos work... but that still involves touching the rodent, which I'd rather avoid.

I tried adding some of my most common key-combos (that should not conflict with anything I do in x-terminal) to x-terminal. But it didn't work.

keymap.cson
```
'.platform-linux x-terminal':
  'ctrl-t': 'fuzzy-finder:toggle-file-finder',
```
The above did not work.
Also I see there is no x-terminal activity or whatever it's called to make it lose focus? Because that could be a badass alternative, so that I don't need to use a mouse.

So workflow would go like this.
1. Finish working in terminal.
2. Press magic key-combo to make terminal lose focus.
3. Use normal atom key-binding to open a file or the tree-view or whatever.

Thanks, any tips or ideas will be appreciated!

**Comment by UziTech** [comment]
This is something that has bugged me as well for a while. I like the idea of having an "unfocus" command. I created PR #141 that should fix this.

**Comment by softwarecreations** [comment]
Brilliant, works amazingly, thanks!
