### ISSUE TITLE
x-terminal ignores alias in .zprofile on macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by ghost** [bus-stop/x-terminal#142]
I can’t use aliases like "composer" or "npm" inside x-terminal. Result: “zsh: command not found: composer”.

It works with the (default) mac terminal, but not with x-terminal.

**Comment by UziTech** [comment]
can you provide your x-terminal config?

**Comment by ghost** [comment]
<img width="762" alt="settings-1" src="https://user-images.githubusercontent.com/2291224/90786014-59d8aa00-e303-11ea-9c54-9069157d38c2.png">
<img width="772" alt="settings-2" src="https://user-images.githubusercontent.com/2291224/90786004-56452300-e303-11ea-8709-7ed320d96190.png">

**Comment by UziTech** [comment]
All x-terminal does is launches the shell and transfers the characters to and from the shell.

I have never used zsh but this seems like an issue loading the startup files. Maybe there is an environment variable that needs to be set? or a parameter that needs to be sent when launching the shell?

**Comment by the-j0k3r** [comment]
I wonder if using `~/.bash_profile` would work, if it does we know the issue is likely xterm side

**Comment by ghost** [comment]
When I open the mac terminal I’m getting:
`/Users/…/.zprofile:source:1: too many open files: /Users/…/.zprofile`
Any idea?

**Comment by the-j0k3r** [comment]
@JonathanDoelan have you tried  doing  `echo source ~/.bash_profile > ~/.zshenv && source ~/.zshenv`  dont forget to backup existing configs beforehand.

**Comment by UziTech** [comment]
I'm going to close this as it doesn't seem like an issue we can fix in x-terminal.
