### ISSUE TITLE
[FR] Keyboard Controls

### ISSUE THREAD

**Issue by jeff-hykin** [bus-stop/x-terminal#144]
### Additional context
Normally I'd use a command to toggle/focus on a terminal panel, similar to focusing on the tree view. But with x-terminal the shortcuts just keep opening new terminals (no toggle or focus command, just open-new). There doesn't seem to be an alternative command. Similarly, I don't see a command/keybinding for closing a terminal.

I'm not sure how other people use this extension without a mouse.

### Describe the feature you'd like
A command to focus on the last-opened terminal.
A command to close a terminal.
If these get added I can finally switch from terminus to x-terminal.

**Comment by UziTech** [comment]
There are commands `x-terminal:close` and `x-terminal:close-all` that closes the terminal. Alternatively if you "exit" the terminal it will close the x-terminal pane.

I don't think there is a way to toggle the terminal currently, other than the toggle dock commands created by Atom. We could add a command like `x-terminal:focus` that focuses a terminal. Though it might be difficult to know which terminal they want to focus if they have multiple terminals open.

PRs are always welcome 😁

**Comment by jeff-hykin** [comment]
Thanks, I'll look into a PR!

**Comment by UziTech** [comment]
`x-terminal:focus` was added in v10
