### ISSUE TITLE
[FR] Mention the Node version

### ISSUE THREAD

**Issue by jeff-hykin** [bus-stop/x-terminal#146]
Can you add the node version you used to the package.json?
```
  "dependencies": {
    "node": "11.1.0",  // <- something like this
    "deep-object-diff": "^1.1.0",
    "fs-extra": "^9.0.1",
    "marked": "^1.1.1",
    "node-pty-prebuilt-multiarch": "^0.9.0",
    "uuid": "^8.3.0",
    "whatwg-url": "^8.2.0",
    "xterm": "4.8.1",
    "xterm-addon-fit": "0.4.0",
    "xterm-addon-web-links": "0.4.0",
    "xterm-addon-webgl": "0.8.0"
  },
```

If I build the extension with node 12, it fails with this error:
```
The module '*bunch-of-stuff*/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 70. 
```

If I build the extension with node 10, it fails with this error:
```
The module '*bunch-of-stuff*/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 68. This version of Node.js requires
NODE_MODULE_VERSION 70. 
```

**Comment by jeff-hykin** [comment]
For any one else running into this issue, I ended up fixing it using [this](https://stackoverflow.com/a/52796884/4367134)

**Comment by UziTech** [comment]
It uses whatever version of node that Atom uses. If you are trying to build this package to use in atom run `apm rebuild` after `npm i` as mentioned in [the docs](https://github.com/bus-stop/x-terminal#development).

**Comment by jeff-hykin** [comment]
My bad, thank you for redirecting me to the docs!
