### ISSUE TITLE
sudo is not working in x-terminal anymore

### ISSUE THREAD

**Issue by softwarecreations** [bus-stop/x-terminal#148]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [x] I have not tried uninstalling/reinstalling the terminal.
### Description
Can't use `sudo` in x-terminal anymore. It worked previously.
I used be be able to run `sudo service foo restart` in the terminal, but now _all_ sudo commands fail, even a simple `sudo -s` fails.

### Steps to reproduce
`sudo -s`

**Expected behavior:**
`[sudo] password for bob: `

**Actual behavior:**
`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

**Reproduces how often:**
Every time.

### Versions

```
> atom --version
```
Atom    : 1.50.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

```
> apm --version
```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 2.7.16
git 2.20.1

OS name and version: Debian 10 Buster (Linux)
Terminal version: 9.1.1

### Additional context
`sudo` works fine in a normal gnome-terminal. If I compare `printenv` with the x-terminal in atom vs gnome-terminal, the following environment variables are different in the atom x-terminal. (atom x-terminal values are shown)

```
ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=true
ATOM_HOME=/home/bob/.atom
CHROME_DESKTOP=Atom.desktop
DISPLAY=:50.0
SHLVL=3
NODE_PATH=/usr/share/atom/resources/app.asar/exports
```

**Comment by the-j0k3r** [comment]
This is an electron 5.x issue see https://github.com/bus-stop/terminus/issues/84

Nothing to be done here,https://github.com/atom/atom/pull/21079 is merged and will fix the issue once Atom releases a production build with electron 6.x

**Comment by the-j0k3r** [comment]
Also see https://github.com/atom/atom/issues/20819 if interested in bug.
