### ISSUE TITLE
[BR] Using C:\Program Files\Git\git-bash.exe opens as external term

### ISSUE THREAD

**Issue by the-j0k3r** [bus-stop/x-terminal#15]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [x] I have not tried uninstalling/reinstalling the terminal.
### Description

Defining a profile or plain settings to use git-bash.exe opens an external terminal

### Steps to reproduce

1. Enter C:\Program Files\Git\git-bash.exe as command path
2. Ensure no Arguments are used
3.Open a terminal

**Expected behavior:**

Terminal to open with x-terminal

**Actual behavior:**

Opens an external terminal

**Reproduces how often:**

1000% <- (900% exaggeration)

### Versions

```
> atom --version

Atom    : 1.44.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> apm --version

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.44.0
python 
git 2.25.0.windows.1
visual studio 
```
OS name and version: Windows 10 Pro 1809 build 17763.1039
Terminal version: 8.6.0

### Additional context

![generic](https://user-images.githubusercontent.com/31389848/75623558-57df2b00-5bab-11ea-9bb8-9d4738b5b855.gif)

**Comment by the-j0k3r** [comment]
Theres many many bugs around this with/without profiles Will need to open individual bugs as Im able, Two of the most prominent Im able to reproduce fairly often.

1) Any preset arguments are loaded with profiles even if profile defines none. 

I had to remove any arguments (for powershell `[ "-NoLogo", "-Mta" ]` ) in main settings to be able to open this bash term profile or command line profile. 

2) many times opening terminals fonts (in prompt area) are garbled or in wrong order, cosmetic rendering issue only.

**Comment by the-j0k3r** [comment]
Are you able to use git-bash?

terminus opens this internally like the others here. =( just thought to mention.

**Comment by UziTech** [comment]
It pops out to a new terminal for me too. But it does that with terminus as well so I'm guessing there isn't anything that we can change in the package to fix that.

![git-bash](https://user-images.githubusercontent.com/97994/76662115-1bb4ae80-654b-11ea-9d2f-f7972b75b2c0.gif)

**Comment by the-j0k3r** [comment]
Works for me in terminus, or use to at least. I'll retest terminus

**Comment by UziTech** [comment]
@the-j0k3r can we close this? I don't think there is anything we can do in x-terminal to prevent this.

**Comment by UziTech** [comment]
If this can turns out to be an issue in x-terminal we can reopen it.

**Comment by the-j0k3r** [comment]
Thats OK, I need a more reliable terminal in Atom not less reliable.

**Comment by UziTech** [comment]
That's why there are multiple terminals. Use whichever one works for you.

**Comment by the-j0k3r** [comment]
I thought xterm based would be less problematic, but I guess not in these cases, weird.
