### ISSUE TITLE
[BR] Cannot run test script

### ISSUE THREAD

**Issue by the-j0k3r** [bus-stop/x-terminal#17]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [x] I have not tried uninstalling/reinstalling the terminal.
### Description

Running `npm run test` results in Atom error

### Steps to reproduce

1. Install project deps `npm i`
2. run `npm run test`
3. See error popup

**Expected behavior:**

No error

**Actual behavior:**

error

**Reproduces how often:**

always

### Versions

```
> atom --version

Atom    : 1.44.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> apm --version

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.44.0
python 
git 2.25.0.windows.1
visual studio 
```
OS name and version: Windows 10 Pro 1809 build 17763.1039
Terminal version: 8.6.0

### Additional context

![Capture](https://user-images.githubusercontent.com/31389848/75671393-ecff2400-5c7e-11ea-99fa-b4c655a8dffc.PNG)

**Comment by UziTech** [comment]
hmm. This works fine for me. I'm on Atom 1.45.0-beta0

![image](https://user-images.githubusercontent.com/97994/75688054-63425d00-5c64-11ea-9533-11d388f6e92b.png)

**Comment by the-j0k3r** [comment]
Atom stable here, and doesnt :/

Also same error when opening the x-terminal directory as defined in https://github.com/bus-stop/x-terminal#development

atom --dev path https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#running-in-development-mode

exact same error

**Comment by UziTech** [comment]
I just tested it on 1.44.0 and it works for me. Maybe something with your setup in a VM?

**Comment by the-j0k3r** [comment]
Its a Windows 1809 production standard install of OS + Atom only in VM. Theres no issues with any other projects. And I have many.

/me shrugs

**Comment by UziTech** [comment]
using `npm ls nslog` it looks like x-terminal (or it's dependencies) doesn't use the `nslog` module so i don't know where that is being called.

**Comment by the-j0k3r** [comment]
https://github.com/atom/atom/blob/d7f7b4f0aa4096df04e88a1b5f8e5e6887e96143/src/main-process/start.js#L2

**Comment by the-j0k3r** [comment]
```log
~\.atom\packages\x-terminal [master ≡]> npm install nslog -g

> nslog@3.2.0 install C:\Users\Joker\AppData\Roaming\npm\node_modules\nslog
> node-gyp rebuild


C:\Users\Joker\AppData\Roaming\npm\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\
node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (
node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\conf
igure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\confi
gure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Joker\AppData\Roaming\npm\node_modules\nslog
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nslog@3.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joker\AppData\Roaming\npm-cache\_logs\2020-03-02T16_14_09_648Z-debug.log
~\.atom\packages\x-terminal [master ≡]>

```
This is just insane, npm cache is gone so no stale anything

**Comment by UziTech** [comment]
This doesn't seem to be an issue with x-terminal so I am going to close this to keep the issues clean.

**Comment by the-j0k3r** [comment]
Still an issue in Atom 1.45.0, probably VM related? Need to test in fresh VM to investigate.

**Comment by the-j0k3r** [comment]
What setup did you do to be able to run `atom --spec test` locally? And have you tested when you dont have a beta atom version installed?

I ran `npm install` and `npm install --only=dev` or `--only-dev` and the nslog error fails.

I have now been able to install nslog globally @3.2.0 but the error still exists.

reinstalled Atom error persists.

**Comment by UziTech** [comment]
Does the same thing happen in other terminals on your setup?

**Comment by UziTech** [comment]
I am on Windows 10. I just uninstalled atom-beta v1.46.0-beta0 and installed atom 1.45.0 and it worked just fine.

**Comment by the-j0k3r** [comment]
Ive opened an issue upstream https://github.com/atom/atom/issues/20511
