### ISSUE TITLE
[BR] Terminal Focus doesn't create new window

### ISSUE THREAD

**Issue by jeff-hykin** [bus-stop/x-terminal#178]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Description

@UziTech I see your test in the PR that should cover this case, so I'm not sure how this behavior is happening. But, after doing all the normal restarting/refreshing/reinstalling calling terminal focus still doesn't create a new window for me.

### Steps to reproduce
1. Open A Folder/Project
2. Call the terminal-focus command with a keybind

**Expected behavior:**
New x-terminal window 

**Actual behavior:**
If I call terminal-open it'll open up a new terminal in the bottom panel, but terminal-focus does nothing. (I have no other terminals open in any other pane). Errors in the console are a different extension (no errors from x-terminal).
![Screen Shot 2020-10-07 at 10 11 48 AM](https://user-images.githubusercontent.com/17692058/95350799-2daec380-0886-11eb-8eb5-10a5e14981fc.png)

**Reproduces how often:**
100%

### Versions
`Atom    : 1.50.0`

OS name and version: Mac Sierra 
Terminal version: 10.0.1

**Comment by UziTech** [comment]
Thanks for reporting this. It looks like the `x-terminal:focus` command was set to only run when x-terminal was already focused. This should be fixed by #179.
