### ISSUE TITLE
Failed to require the main module of 'x-terminal' because it requires one or more incompatible native modules (node-pty-prebuilt-multiarch)

### ISSUE THREAD

**Issue by softwarecreations** [bus-stop/x-terminal#188]
The error
```
Failed to require the main module of 'x-terminal' because it requires one or more incompatible native modules (node-pty-prebuilt-multiarch).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

Appears in atom's inspector console, when I open atom with x-terminal 11.0.2
I'm just making this issue (with the above title) to link to https://github.com/bus-stop/x-terminal/issues/187 to make it easier to find.
Please go to the above issue for discussion/resolution.

**Comment by the-j0k3r** [comment]
The message says all =)

>Run `apm rebuild` in the package directory and restart Atom to resolve.

This means you navigate to `~/.atom/packages/x-terminal` and run the command within an external terminal on this path.

Alternatively, completely uninstalling and re-installing the terminal should also install the correct node-multiarch-prebuilt version.

Note: You dont mention the version of Atom you are using, which is required in the issue template. This is useful info, please provide it. Also if you upgraded Atom recently.

**Comment by the-j0k3r** [comment]
The solution is posted in #187 which is the Alternate solution on my post above (uninstall and reinstall fully x-terminal).

If you fell like blaming something, blame APM and node-gyp which are Atoms projects responsinble for installing/upgrading all things related to Atom extensions. Clearly there are many issues with these packages that affect similar projects like this, and we cant do much about it.
