### ISSUE TITLE
[FR] Send current line to terminal and move cursor to next line

### ISSUE THREAD

**Issue by Kabouik** [bus-stop/x-terminal#20]
### Describe the feature you'd like
After months looking for a terminal I could move in a panel instead of being fixed to the bottom of Atom with the full-window width, I finally found this awesome package. Thanks.

However, I would need to send lines of the editor file into the terminal with a keybinding, pretty much like what Termination does with `alt+r`. Is that possible with x-terminal currently, or with the help of another package?

I see that your other terminal package, Terminus, allows inserting the current selection to the terminal, but `ctrl+enter` didn't do anything on my end and I am not sure what the issue is. Plus, I would prefer something that does not require selecting the line first (just send the line where the cursor is) and that automatically moves the cursor to the next line afterwards.

### Additional context
Any "send-code" variant would be very useful (send all, send selection, send current line, send section, *etc.*) for executing R code for instance, which is my intent, but also for other similar workflows.

**Comment by UziTech** [comment]
That is not currently possible but we are open to pull requests

**Comment by Kabouik** [comment]
Thanks for the answer. I have no idea how to do that unfortunately, I can only write code in R language. That's sad, I really liked what I saw about x-terminal. I will definitely keep an eye on it to be notified if/when this feature is implemented one day.

I'll ask on the Terminus bug tracker how to troubleshoot why `ctrl+enter` has no effect on my machine, maybe that would better meet my requirements if there is a workaround to this issue.

**Comment by UziTech** [comment]
I think the difficult thing about this will be knowing which terminal to run the command in if there are multiple terminals open. It looks like termination can do this because it can only show one terminal at a time.

Maybe we need to track which one was last focused?

**Comment by Kabouik** [comment]
> Maybe we need to track which one was last focused?

Sounds good to me, I think it would be straightforward from a user's perspective. At least for the first iteration, and then maybe using the feature will foster new ideas.

Another way could be to ask the user, when sending code for the first time, which terminal to send the code to if several are already open (no prompt if only one is open), and then pair the edited file to that particular terminal (keep sending code to that terminal even if new terminals are opened later). I think Termination and Terminus already have a pairing system, but I suppose this second option would need much more work.

**Comment by the-j0k3r** [comment]
>Terminus, allows inserting the current selection to the terminal, but `ctrl+enter` didn't do anything on my end.

@Kabouik Yea that's because you're running wrong key bind see https://github.com/bus-stop/terminus/blob/master/keymaps/terminus.cson its definetly not `ctrl+enter` but I see the issue is the readme, so will fix =) Sorry about that.

**Comment by UziTech** [comment]
Oops linked the wrong issue
