### ISSUE TITLE
[FR] Open project folder in terminal

### ISSUE THREAD

**Issue by vivi90** [bus-stop/x-terminal#212]
### Description
For example in the file manager Thunar there is a feature to open a selected folder in a new terminal window by the right mouse button context menu.
I think it would be great, if it's possible to implement this in Atom for the context menu of project folders.

### Possibly connected to:
- https://github.com/bus-stop/x-terminal/issues/38
- https://github.com/bus-stop/x-terminal/issues/96

**Comment by vivi90** [comment]
Sorry, but doesn't working for me.

**Comment by UziTech** [comment]
I think I fixed it in v12.0.1

**Comment by vivi90** [comment]
@UziTech Yes, now it works. But it doesn't restore the correct path at atom restart. After Atom restart, all opened terminals are at the first project folder path.

**Comment by UziTech** [comment]
hmm, that seems like a separate issue. I don't know if keeping track of the cwd of every terminal is possible. There doesn't seem to be anything in xterm that will keep track of when `cd` is used to change directories.

**Comment by UziTech** [comment]
Do you have multiple projects open and a terminal open for each project? That sounds more like something [mapped terminals](https://github.com/bus-stop/x-terminal/issues/38) could solve.

**Comment by UziTech** [comment]
Actually I think #227 will fix it.

**Comment by UziTech** [comment]
Does it work in v12.0.2?

**Comment by vivi90** [comment]
> Do you have multiple projects open and a terminal open for each project? That sounds more like something [mapped terminals](https://github.com/bus-stop/x-terminal/issues/38) could solve.

Yes and no. Sometimes i work on multiple projects in Atom at the same time. But for some projects i need multiple terminals.

> Does it work in v12.0.2?

Yes, it works! 
Great work like i know it from you :slightly_smiling_face: 

If you are looking for an additional project to maintain, there are currently issues with this one:
https://github.com/thomasjo/atom-latex/issues/542#issuecomment-726981031 :wink:
