### ISSUE TITLE
Clear terminal[FR] 

### ISSUE THREAD

**Issue by johann1301s** [bus-stop/x-terminal#214]
### Describe the feature you'd like

The command cmd-k does not clear the existing commands entered in the terminal like it does using the native macOS terminal.

Add a way to clear the terminal, preferably cmd-k.

### Additional context

The _clear_ command works but is more cumbersome than cmd-k.

**Comment by UziTech** [comment]
You can use [terminal-commands](https://atom.io/packages/terminal-commands) to create a command that sends `clear` to the active terminal. Then use keymaps to assign keys to the command.

**Comment by UziTech** [comment]
I created PR #216 which adds `x-terminal:clear` I'm not sure if it works better than doing something with terminal-commands.

The biggest problem with a universal clear command is that not all terminals act the same. Using terminal-commands will allow you to create a command that is specific to the terminal that you use.
