### ISSUE TITLE
[FR] Terminal language 

### ISSUE THREAD

**Issue by gregBerthelot** [bus-stop/x-terminal#237]
### Describe the feature you'd like

I would love to change the terminal language. On VSCode we can set display=en which force the terminal to use `en` language. 

### Additional context

Currently **X terminal** uses system language and does not handle well special chars eg. `git pull`  result in  **_D'eja a jour._** instead of **_Déjà à jour_** for French which means **_Already up to date_**

**Comment by UziTech** [comment]
Would changing the font work? I don't understand what you mean by changing the language.

**Comment by the-j0k3r** [comment]
>result in D'eja a jour. instead of Déjà à jour for French which means Already up to date

Isn't that a translation issue? I think so, and thus not the right tree. AFAIK thats a git translation problem

**Comment by UziTech** [comment]
There is a Character Encoding setting that might be what you are looking for.

![image](https://user-images.githubusercontent.com/97994/103942655-5731f200-50f6-11eb-9d98-6545648163e7.png)

**Comment by the-j0k3r** [comment]
Just wanted to point out that to confirm its a translation issue, you could run the same command on external terminal.

**Comment by gregBerthelot** [comment]
In external Terminal we can change language with eg `LANG=en_us_8859_1` to set terminal in english. That does not work on Xterminal.


> > result in D'eja a jour. instead of Déjà à jour for French which means Already up to date
> 
> Isn't that a translation issue? I think so, and thus not the right tree. AFAIK thats a git translation problem

Seems more to be an encoding issue. I tested Terminus which is using english language by default

**Comment by gregBerthelot** [comment]
`git pull` command:

1. in X Terminal => D'eja 'a jour (wrong)
2. Terminus => Already up to date (good)
3. Mac OS Terminal => Déjà à jour (good)
4. Mac OS Terminal after running `LANG=en_us_8859_1` => Already up to date (good)

**Comment by the-j0k3r** [comment]
> Seems more to be an encoding issue. I tested Terminus which is using english language by default

Terminus sets UTF8 for macOS https://github.com/bus-stop/terminus/search?q=language and sets language to English US

So you probably should set UTF-8 in x-terminal too and test, like you already been suggested earlier.Also you can try to export environment variables in x-terminal and ensure its set at startup.

Just out of curiosity, is Atom in French on your system?

**Comment by gregBerthelot** [comment]
tested `UTF-8` encoding and get the same issue. Atom is in English

**Comment by the-j0k3r** [comment]
Have you tried exporting the environment path for language within Atom?

There's guides on the web.

**Comment by the-j0k3r** [comment]
Also https://xtermjs.org/docs/guides/encoding/

**Comment by UziTech** [comment]
@gregBerthelot have you been able to get this to work with the information in https://xtermjs.org/docs/guides/encoding/?

**Comment by gregBerthelot** [comment]
Unfortunately not

**Comment by UziTech** [comment]
You said it is working in `terminus` but not in `x-terminal` but the only thing I can tell that terminus does differently is setting the environment variable `LANG` in https://github.com/bus-stop/terminus/blob/3990b9c1795a5b8d915eee702dd53f991d1ed3c5/lib/process.js#L21

Have you tried setting `{LANG: 'en_us_8859_1'}` in the Environment Overrides setting? This should accomplish the same thing as terminus.

**Comment by UziTech** [comment]
Seemed to work to export LANG in WSL

![image](https://user-images.githubusercontent.com/97994/105077532-44061700-5a52-11eb-9169-90861b2330b0.png)

**Comment by gregBerthelot** [comment]
I tested in X terminal setting > Character Encoding and Environment Overrides and that does not work. That means we need to do `export LANG=en_us_8859_1` on each new terminal instance in terminal window itself

**Comment by the-j0k3r** [comment]
> I tested in X terminal setting > Character Encoding and Environment Overrides and that does not work

How did you actually input the required export? Did you use the format provided or decided to do your own thing?

**Comment by gregBerthelot** [comment]
![CleanShot 2021-01-21 at 11 34 57](https://user-images.githubusercontent.com/19594443/105339274-c9b5ce00-5bdc-11eb-982e-e17b8af82d2c.png)

**Comment by the-j0k3r** [comment]
A json object... So I think its

`{"LANG": "en_us_8859_1"}`

**Comment by gregBerthelot** [comment]
Oh my bad… works fine. Thanks for your help :)

**Comment by the-j0k3r** [comment]
No problem. Glad it works and feature already implemented.
