### ISSUE TITLE
Django ENV does not appear activated 

### ISSUE THREAD

**Issue by samsonia8800** [bus-stop/x-terminal#254]
### I would like to be able do the following

1. Activate a newly created Django vEnv per docs.conda.io instruction "conda activate myenv"
2.
3.

**Comment by UziTech** [comment]
- What have you tried?
- Does it give you an error message?
- Does it work in a regular terminal from the same working directory?
- What OS are you using?

**Comment by the-j0k3r** [comment]
@UziTech youre a better person than I, asking questions that should have been part to the issue template which was ignored.

Marking as invalid for now.

**Comment by samsonia8800** [comment]
Disregard rookie w/o nuki; 

Mistake due to public education;

Resolved by referencing more public education;


CyberPunk
