### ISSUE TITLE
[BR] Impossible to uninstall/reinstall x-terminal

### ISSUE THREAD

**Issue by ilboia** [bus-stop/x-terminal#326]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Description

I am unable to uninstall x-terminal after it stopped working, neither of course to reinstall it. Until yesterday (11/06/2021)
it was working fine. It's like atom doesn't see at all the x-terminal plug-in
Thanks

### Steps to reproduce

1. Open Atom V 1.57.0
2. x-terminal doesn't show up in the package menu 
3. click on uninstall not working

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Versions

```
> atom --version

```

```
> apm --version

```
OS name and version: Windows 10 Family, v 10.0.19042 build 19042
Terminal version:

**Comment by UziTech** [comment]
Their is most likely a process that was started by x-terminal that is frozen.

Restart your computer and try re install again.

**Comment by nichlock** [comment]
Had the same issue where something must have frozen and it wouldn't show up anywhere. Rebooting did not work for me, but with Atom closed, I was able to reinstall using apm.

```
apm remove x-terminal
apm install x-terminal
```

The above worked for me in Powershell. 

---

Versions:

> Version 10.0.19041 Build 19041
> x-terminal@13.0.10
> apm  2.6.2
> atom 1.57.0

**Comment by the-j0k3r** [comment]
Bad install or upgrade, the gremlins, =) Try this below;

1. Close Atom (all instances)
1. Remove `~/.atom/packages/x-terminal`
1. run on an external terminal `apm install x-terminal`
1. Open Atom profit

Other than that we are at the mercy of apm afaik.

**Comment by ilboia** [comment]
Thank you for the answers. The only one that worked was the last one from the-j0k3r. I did:

1. `rm ~/.atom/packages/x-terminal`
2. and then `apm install x-terminal`

I only hope it's not going to do it every time I shut down a kernel or something similar (one of my kernels is running on an external hard drive, so sometimes unfortunately it gets disconnected). 

Anyway thank you.
