### ISSUE TITLE
[FR] Toggle

### ISSUE THREAD

**Issue by calvinbui** [bus-stop/x-terminal#430]
### Describe the feature you'd like

The ability to toggle (open/close) the terminal. This was a feature in terminus.

### Additional context

Default on Mac was ```ctrl-` ``` : https://github.com/bus-stop/terminus/blob/master/keymaps/terminus.cson#L16

**Comment by UziTech** [comment]
I'm not sure "toggle" really makes sense in x-terminal. In Terminus there was only one terminal open at a time and it was in it's own panel.

X-Terminal is meant to be in a dock with other items and there can be multiple each open at the same time in different docks or even multiple open in the same dock. What does it mean to "toggle" x-terminal when it is in a doc? should it close the dock? should it activate a different item in the dock?

There is already a "focus" and "unfocus" command as well as commands to open and close docks. I think it is better for users to use the specific command that works for them.

**Comment by calvinbui** [comment]
The idea was there would be a key to both open and also close the terminal as needed. 

Toggling on Terminus worked similar to all the other toggles Atom provided, like the Git tab or Tree view.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/3604363/158934096-fff56d35-3c0a-477b-97ce-a1d48f109f40.png">

**Comment by UziTech** [comment]
There already is a command for `Window: Toggle Bottom Dock`.

**Comment by UziTech** [comment]
What would the "toggle" command do for a user with a setup like:

![image](https://user-images.githubusercontent.com/97994/158934660-f01ca514-d091-4b48-8409-398da0b50467.png)

That is why we need the more specific commands that we already have.

**Comment by the-j0k3r** [comment]
> I'm not sure "toggle" really makes sense in x-terminal. In Terminus there was only one terminal open at a time and it was in it's own panel.

You still can have multiple terminals just fine with terminus, You didnt have any other way to open the terminal in a specific position besides dragging it there or onto the bottom/left/righ docks but you can indeed have multiple terminals just fine. Its not as sophisticated obviously.

![Capture](https://user-images.githubusercontent.com/31389848/158960456-8f4bd9d3-920f-4b2e-9d33-c86b193c6fa4.PNG)

x-terminal you still cant [map terminals to files or folders](https://github.com/bus-stop/terminus#map-terminal-to) which was one of the most useful features which made more sense when toggling imo.

**Comment by UziTech** [comment]
@the-j0k3r so what would toggle do in the situation you are describing with multiple terminals open?

**Comment by the-j0k3r** [comment]
Wait, sorry I confused toggle with prev/next.

**Comment by the-j0k3r** [comment]
However, when you have a specific terminal open you may want to hide it, terminus just created  a terminal if none existed on first toggle, there after it either hid or showed the respective terminal in focus, x-terminal just keeps creating new terminals on toggle.

I would say this could be a either or option on x-terminal, where e.g. 
Toggle Behavior >
Create a terminal if none exists then show/hide focused terminal (terminus behaivior)
Create a new terminal (x-terminal behavior)

**Comment by UziTech** [comment]
Which terminal should be focused or hidden on "toggle" in your image?

**Comment by the-j0k3r** [comment]
In that image none were focused if you notice the position of the cursor on the git portion of the commit message, But pick any.

**Comment by UziTech** [comment]
Seems like a command that is toggles a random terminal wouldn't be very useful. I would rather have the user use commands that already exist to toggle the one that they want.

**Comment by the-j0k3r** [comment]
Not a random terminal, the one which has current focus. Thats the point. You dont need yet another command terminus used Ctrl+` for both jobs, if the term is focused the hides, if not shows the one focusedd last.

**Comment by UziTech** [comment]
There are already commands for that. "focus" and "unfocus" are already commands that can be mapped to the same key because they are scoped to whether or not a terminal is focused.

If someone wants to work on this and come up with solutions to every possible meaning for the word "toggle" I will happily accept a PR. But I don't see how that is going to work with a single command.

P.S. I just tested "toggle" in terminus with multiple terminals open and it only toggles the one in the original pane. So if you want toggle to work the same as terminus you can just use the "Window: Toggle Bottom Dock" command.

**Comment by calvinbui** [comment]
i'm going back to Terminus
