### ISSUE TITLE
[FR] Close tabs with Control W 

### ISSUE THREAD

**Issue by codic12** [bus-stop/x-terminal#54]
Terminal tabs should be able to close with Ctrl W as per the standard atom bindings.

**Comment by mediafinger** [comment]
You should already be able to add a keybinding to achieve this. Here my macOS example, which should work under Windows with minor changes:

```
'.platform-darwin x-terminal':
  'cmd-w': 'x-terminal:close'
  ```

**Comment by codic12** [comment]
Excellent. I don't use Atom anymore but in this case I will close the issue.
