### ISSUE TITLE
[Q] paste text from the clipboard into a file created in the terminal

### ISSUE THREAD

**Issue by tsimur** [bus-stop/x-terminal#56]
### I would like to be able do the following

1.When I paste text from the clipboard into a file created in the terminal, the line breaks disappear and as a result the text is not inserted correctly. How can I configure the X terminal so that line breaks do not disappear?

**Comment by UziTech** [comment]
Can you provide example steps?  and os version and terminal used (i.e. bash, zsh, etc)?

**Comment by UziTech** [comment]
I'm going to close this as there was no response. If this is still an issue feel free to reopen it and provide the necessary information for us to debug it.
