### ISSUE TITLE
shortcuts:  issues with some terminal open key-combos (Windows)

### ISSUE THREAD

**Issue by the-j0k3r** [bus-stop/x-terminal#6]
Not working to open terminal

    "ctrl-`": "x-terminal:open",
    "ctrl-~": "x-terminal:open",

![generic](https://user-images.githubusercontent.com/31389848/75242110-c09f5f80-57c7-11ea-9b93-5227633c13e3.gif)

Haven't tested in other OS

The OSK initially I thought if I used regular keyboard would show the keys I was pressing, No other reason, It works exactly the same as physical keyboard though.

**Comment by UziTech** [comment]
strange it works for me. Try opening `Key Binding Resolver` (<kbd>Ctrl</kbd> + <kbd>.</kbd>) and seeing if some other key binding is taking precedence.

**Comment by the-j0k3r** [comment]
OK this is weird.

`ctrl`-`~` works but...... not like that,  -like that I get `ctrl`-`#`

On my keyboard this key is `#~` with  `~` at the top, to get `~` I have to press `shift` + `#~` so really the the shortcut from me looks like `ctrl`-`shift`-`~` even though the keybind resolver looks like the actual `ctrl`-`~` and not `ctrl`-`shift`-`~`

I wonder is this expected behavior? 

Still ``ctrl-` ``does nothing no matter how I slice it. terminus one works oddly enough.

![generic](https://user-images.githubusercontent.com/31389848/75322053-5c85a580-5872-11ea-9d7e-fa2f672691c3.gif)

**Comment by the-j0k3r** [comment]
Also pressing and holding the open keycombo for mmm say a fraction of a second more you get a ton of terminals.

So best not let your cats do the typing for you.

![generic](https://user-images.githubusercontent.com/31389848/75322626-6b208c80-5873-11ea-8393-27c2afd37640.gif)

Hidden feature

**Comment by UziTech** [comment]
Just locked up my computer testing it out 😆

We should probably fix that.

**Comment by the-j0k3r** [comment]
turns out its ctrl +` not ctrl +' like terminus so all work with the caveat above. for ctrl - ~
