### ISSUE TITLE
[Q] Help with using x-terminal in Juno

### ISSUE THREAD

**Issue by aminya** [bus-stop/x-terminal#65]
Juno-ide (Julia) now uses its own terminal in atom-ink and atom-julia-client. But to make the those packages modular, it is a great idea to make them simpler and instead use x-terminal. This way each group can focus on more specific things.

Could you help us with this move?
https://github.com/JunoLab/atom-julia-client/issues/744

https://github.com/JunoLab/atom-ink/tree/master/lib/console
https://github.com/JunoLab/atom-julia-client/tree/master/lib/connection

**Comment by UziTech** [comment]
What do you need us to help with? Users can already have both packages installed and just use whichever console they want.

I don't understand what you want x-terminal to change to help you with this.

**Comment by aminya** [comment]
I don't have a specific thing to change, but some stuff may arise as we go through this process. I checked #23 which is a very useful feature and will probably simplify Juno more.
This is more like a discussion kind of issue I created for future use. 😄

**Comment by UziTech** [comment]
I would prefer issues be more about specific things that need to be added or fixed. I tend to use the issues as a backlog of things to do. I am going to close this, but feel free to open feature request issues (or better yet PRs) if there is something you would like to see added to x-terminal.

**Comment by aminya** [comment]
> I would prefer issues be more about specific things that need to be added or fixed. I tend to use the issues as a backlog of things to do. I am going to close this, but feel free to open feature request issues (or better yet PRs) if there is something you would like to see added to x-terminal.

Sure. That is not a problem. For sure I will make more specific features here as we discover them.
