### ISSUE TITLE
[Q] openTerminal command not working?

### ISSUE THREAD

**Issue by aminya** [bus-stop/x-terminal#67]
I tried to use `atomXtermService`, but it returns an error.
```js
   function useterminal() {
    atomXterm.openTerminal({
      command: 'julia'
    });
  };
```
![image](https://user-images.githubusercontent.com/16418197/81428799-6b19f400-9122-11ea-981d-54b1a2cb761b.png)

However, `platformioIDETerminalService` works perfectly fine. Am I missing something?
```js
   function useterminalPIDE() {
    console.log("hello world");
    platformioIDETerminal.run(['julia']);
  };
```
![image](https://user-images.githubusercontent.com/16418197/81429093-eaa7c300-9122-11ea-801e-d565ae99e95f.png)

**Comment by UziTech** [comment]
The `command` options should be a shell to start (i.e. `cmd`, `powershell`, `bash`, etc.)

The `atomXtermService` is for starting up terminal with a given profile. The `platformioIDETerminalService` uses the default profile to run the commands.

**Comment by aminya** [comment]
@UziTech Nothing was mentioned in the Readme. I thought they are just two different syntaxes. Could you add documentation about `openTerminal` to the readme? or a link that shows the possible options. Without documentation, people cannot integrate `openTerminal` into their packages.

**Comment by UziTech** [comment]
I think this is fixed with the new terminal service.
