### ISSUE TITLE
Import x-terminal to fix GitHub Searches into project

### ISSUE THREAD

**Issue by the-j0k3r** [bus-stop/x-terminal#8]
Currently if you search on this project for anything you get 0 hits, Forked projects dont get any searches, none.

![Capture](https://user-images.githubusercontent.com/31389848/75247050-58ee1200-57d1-11ea-8503-8e578e7c618e.PNG)

If the repo is imported/ instead of forked this isnt a problem see https://github.com/the-j0k3r/x-terminal-fork-fix-gh-project-search/search?q=test&unscoped_q=test

![Capture](https://user-images.githubusercontent.com/31389848/75247106-79b66780-57d1-11ea-8baa-6cc80d4551a7.PNG)

:+1: :tada: 

To do this goto Create a new repo and select import at the top

![generic](https://user-images.githubusercontent.com/31389848/75246697-9c944c00-57d0-11ea-8471-ba663ba49547.gif)

Nothing is lost then simply making transition from one to other should be seamless.

An alternative way is to create a new empty repo and add a remote and rebase also very doable.

**Comment by the-j0k3r** [comment]
Also I can just transfer my import of this to you, it saves you the work, just need to rename the project after you remove this one.

Edit Ive initiated this transfer to you =)

Or alternatively transfer to bus-stop org where you can admin/dev it there.

**Comment by UziTech** [comment]
I think it would be best to transfer it to bus-stop. Do you know if there is a way to change the repository but keep the package name on atom?

**Comment by UziTech** [comment]
It looks like if I just transfer the repo to bus-stop the upstream fork will remain. https://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership

I wonder if it would work to rename the repo, import it into the same name (`UziTech/x-terminal`), then transfer it?

**Comment by the-j0k3r** [comment]
I can export directly to bus-stop with x-terminal name, I simply rename it to x-terminal and transfer.

**Comment by UziTech** [comment]
yes but will APM allow you to publish from the new repo?

**Comment by the-j0k3r** [comment]
Yes, Termination was imported into bus-stop, besides readme links nothing else changed.

I think you can even yourself export it to bus-stop directly, its the same procedure as above, I imported into my own account not the org as I wasnt sure if thats was OK with you.

**Comment by UziTech** [comment]
But if I transfer it how it is right now the upstream fork will remain according to https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by the-j0k3r** [comment]
You dont transfer it, you import it ;) Goto https://github.com/organizations/bus-stop/repositories/new  and on the next page on the top


>Create a new repository
>
>A repository contains all project files, including the revision history. Already have a project repository elsewhere? [Import a repository.](https://github.com/new/import)

No upstream fork will be marked just like in my test import instance

**Comment by UziTech** [comment]
I imported it to bus-stop. https://github.com/bus-stop/x-terminal

I'll try publishing a new version with the new repo

**Comment by UziTech** [comment]
I don't think there is a way to make APM look for the package at the new repo without transferring it.

**Comment by the-j0k3r** [comment]
It worked for Termination...

**Comment by UziTech** [comment]
I renamed it imported and transfered it. hopefully that works

**Comment by the-j0k3r** [comment]
Seems like its working OK building at least.

**Comment by UziTech** [comment]
ya and now the repo link on atom.io goes to bus-stop

**Comment by the-j0k3r** [comment]
More than that https://atom.io/packages/x-terminal the link

[repo](https://github.com/UziTech/x-terminal) redirects to bus-stop/x-terminal, so my guess is the rest will be updated by the first release from there.

**Comment by the-j0k3r** [comment]
You beat me to it.

**Comment by UziTech** [comment]
looks like [actions](https://github.com/bus-stop/x-terminal/runs/468006239?check_suite_focus=true) is failing to push the new tag to APM 

```
Git tag not found
```

Maybe APM just needs time to update it's cache?

**Comment by the-j0k3r** [comment]
![Capture](https://user-images.githubusercontent.com/31389848/75336111-d9247e00-588a-11ea-8aab-c5369f3b4ea5.PNG)

Seems fully updated, I received 8.0.2 and it points all to bus-stop, Maybe it needed time to spread.

**Comment by the-j0k3r** [comment]
Mk log for https://github.com/bus-stop/x-terminal/runs/469502934?check_suite_focus=true says

>The local branch master is behind the remote one, therefore a new version won't be published

You may want to check that remote is not set to this repo or something else, since 8.0.3 is not on offer yet.

Edit: my query shows only the expected
```
origin  https://github.com/bus-stop/x-terminal.git (fetch)
origin  https://github.com/bus-stop/x-terminal.git (push)
```

I also rerun the workflows on the failed actions, all are green now.

**Comment by the-j0k3r** [comment]
Im also wondering about the semantic release bot, doesn't it have to be installed in project?

**Comment by UziTech** [comment]
it is installed as a devdependency

**Comment by the-j0k3r** [comment]
Well idk why it wont publish 8.0.3

**Comment by UziTech** [comment]
seems like it is a common issue with APM https://github.com/atom/apm/issues/873

looks like we need an admin to change the repo on their server.

**Comment by the-j0k3r** [comment]
> looks like we need an admin to change the repo on their server.

admin to what?

**Comment by UziTech** [comment]
admin to atom.io

**Comment by UziTech** [comment]
https://github.com/atom/apm/issues/870#issuecomment-542980198

**Comment by the-j0k3r** [comment]
Im perplexed. Termination was done under same circumstances, except it not running automated releases or actions. See https://github.com/bus-stop/Termination/commits/master it was as simple as that. Zero issues with this.

have you tried a manual release via apm publish? I think that may just do it. :tm: famous last words worth a shot maybe.

**Comment by UziTech** [comment]
same error when trying to publish manually

![image](https://user-images.githubusercontent.com/97994/75357715-6e1d7c00-5877-11ea-9b46-f7db351620f1.png)

**Comment by the-j0k3r** [comment]
hummmm bum! Those failed tags are published though shouldt they be deleted?

**Comment by UziTech** [comment]
I was able to publish v8.0.4 but only after pushing tags to this repo. atom.io's system must use some sort of repo ID instead of path.

That means I could transfer this repo to bus-stop/xterminal but the upstream fork would remain. 😕

**Comment by UziTech** [comment]
looks like we just need to contact support to remove fork.

https://github.community/t5/How-to-use-Git-and-GitHub/De-forking-a-Github-repo/td-p/2785

**Comment by UziTech** [comment]
I'm going to delete bus-stop/x-terminal then transfer this repo and contact support to remove the fork

**Comment by the-j0k3r** [comment]
I guess Ill stop what Im doing then

**Comment by UziTech** [comment]
boom :tada: Actions released v8.0.5 😁👍

**Comment by the-j0k3r** [comment]
Yea it was the setup thingy

**Comment by the-j0k3r** [comment]
yep this issue is not fixed though

**Comment by UziTech** [comment]
true. I submitted a request to remove the upstream fork.

**Comment by the-j0k3r** [comment]
I would have thought fixing atom.io would have been more likely, lets see =)

**Comment by the-j0k3r** [comment]
Seems fixed... That was fast... hopefully releasing still works.
