### ISSUE TITLE
Select on Copy; does not copy

### ISSUE THREAD

**Issue by softwarecreations** [bus-stop/x-terminal#90]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Description
Copy on Select does not work.

### Steps to reproduce
1. I've checked the option "Copy on Select" in bus-stop/x-terminal settings tab in Atom.io
2. I select some text in the terminal, try paste, but it has not copied what I've selected.
3. I confirmed that normal Copy/Paste works. (Ctrl-Insert to copy and Shift-Insert to paste)

**Expected behavior:**
When I click and drag to select some text in the terminal, upon releasing the mouse button, the selected text should be copied to the clipboard.

**Actual behavior:**
The selected text is not copied to the clipboard.

**Reproduces how often:**
100%

### Versions

```
> atom --version
```
Atom 1.47 on Linux x86_64 (Debian 10 Buster)
```
> apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.16
git 2.20.1

```
OS name and version:
Terminal version:
8.2.1

**Comment by UziTech** [comment]
Seems to work fine on Windows 10. This might just be a Linux issue. I will try to debug it in Ubuntu but it might take a few days to get to it.

**Comment by UziTech** [comment]
It seems to work fine on ubuntu an Windows 10. If you can debug it on your system we can try to help fix it but I am unable to reproduce the issue.

![copy-on-select](https://user-images.githubusercontent.com/97994/84458083-d24b2c80-ac29-11ea-9172-8a53ea5d34ad.gif)

**Comment by softwarecreations** [comment]
Very weird, I was using 1.47 because of the MultiCursor Ctrl-Click bug in 1.48.
I saw there's a workaround for the MultiCursor Ctrl-Click so I upgraded to 1.48.

X-terminal 8.2.1 _Copy on select_ worked on Atom 1.48!

BTW I upgraded x-terminal to the latest 8.2.2 and it's still working :)

Thanks!
