### ISSUE TITLE
Add option: Paste selected text instead of clipboard

### ISSUE THREAD

**Issue by softwarecreations** [bus-stop/x-terminal#91]
### Describe the feature you'd like
Add option: "**Paste selected text instead of clipboard**"
When text is selected, and you _x-terminal:paste_ it won't dump the clipboard into the terminal, but rather it will dump the selected text into the terminal. When using this feature, the clipboard is not read from or written to when there is selected text and you press paste. (the clipboard is bypassed).

That way you can have something in the clipboard, but also copy some text that's on the screen in your terminal into the buffer.

Imagine you have a long path in your clipboard.
/very/long/path/very/long/path/very/long/path/very/long/path/

you type `ls`
Then you see a long filename
foo54085034980954809548390854309.txt
so you can simply
1. Type `mv `
2. Select `foo54085034980954809548390854309.txt` with your mouse
3. Press Shift-Insert (that is this feature request, it will copy the selected text to the command string that you're typing)
so now you have `mv foo54085034980954809548390854309.txt`
4. Press space
5. Click inside the terminal to deselect all text.
6. Press Shift-Insert That will paste `/very/long/path/very/long/path/very/long/path/very/long/path/`
7. Press enter

### Additional context
This feature request is not related to the bug: https://github.com/bus-stop/x-terminal/issues/90
But if this feature request is implemented, I would check "Paste selected text instead of clipboard" and I would uncheck "Copy on Select"
That way when you select something, you can optionally copy it Ctrl-Insert or you can just dump it into the terminal without losing what's already in your clipboard.

It would also be great to add another action _x-terminal:deselect-text_ so that you can de-select all text using the keyboard without needing to take your hands off the keyboard to click the mouse. So instead of step 5, you could press ctrl-d or whatever floats your boat.

**Comment by UziTech** [comment]
If you want to create a PR to add that setting I would be happy to review it. 😁

**Comment by softwarecreations** [comment]
Cool, I'll see if I get some time later in the month

**Comment by UziTech** [comment]
@softwarecreations is this still a feature you are working on?

**Comment by softwarecreations** [comment]
@UziTech thanks bud. Need to prioritize other dev work.
