### ISSUE TITLE
Why use the project directory when the cwd is in the project path?[Q] 

### ISSUE THREAD

**Issue by yangybb45142** [bus-stop/x-terminal#96]
For the initialize() in the model.js, why use the project directory when the cwd is in the project path?

**Comment by UziTech** [comment]
I'm not exactly sure what you are referring to. Could you give an example?

**Comment by yangybb45142** [comment]
Thank you for your reply! Sorry, I didn't make it clear。

Line 80 in /src/model.js of x-terminal, there is the following code:
const dir = atom.project.relativizePath(cwd)[0]
if (dir) {
  // Use project paths whenever they are available by default.
  this.profile.cwd = dir
  return
}

I use x-terminal to start java application. I set the Java application directory to the cwd parameter, I encountered two obstacles:
1. Classpath lookup error based on relative path;
2. Log cannot be output to start directory;
I found that the problem was caused by the code above. The code modifies the startup path of Java application。

I want to know why you did that, or if I have a wrong understanding of the cwd parameter?

**Comment by UziTech** [comment]
I'm not sure why that is like that. If you want to create a PR that adds a setting to disable it I would be happy to review it.

**Comment by the-j0k3r** [comment]
This could be solved by [mapping terminal to file](https://github.com/bus-stop/x-terminal/issues/38).

**Comment by UziTech** [comment]
@the-j0k3r PRs are welcome 😁

**Comment by the-j0k3r** [comment]
Preaching to the choir =) there @UziTech? Soon as I know enough to do it, so far Im struggling with catching up from learner to the level needed, never mind the rest.

Also lately more chores needed around the house, so no time for scrambling bits. awww
