### ISSUE TITLE
[FR] Integration with hydrogen and atom-script

### ISSUE THREAD

**Issue by aminya** [bus-stop/x-terminal#97]
### Describe the feature you'd like

It would be nice if hydrogen and atom-script are integrated with Terminal. This can allow evaluating code and getting the result back in a more organized way. This is useful if we want to get runtime information such as workspace data, defined variables, etc.

What I miss here is a connection between language client protocol, terminal, and runners. 

If these connect to each other, we can have a single process (like python or julia), and work with it in Terminal, evaluate code in the editor, and get help from the language server that includes runtime information

**Comment by UziTech** [comment]
I'm not sure what language server you are talking about. I don't see how having workspace data would be useful in the terminal unless you are editing source code, in which case you can just use atom for that.

**Comment by aminya** [comment]
Imagine, there is a python process running and someone defines a variable using terminal
```py
x = 1 
```
Now we want to make a workspace like the following:
![image](https://user-images.githubusercontent.com/16418197/84574973-a6d25a00-ad6f-11ea-825c-2b3fc280b3e0.png)

We also want to offer the same `x` in the autocomplete for a language server.

All of these processes should be connected to each other.

That's why I created https://github.com/bus-stop/x-terminal/issues/65. In Juno, a similar thing is done, but using a custom terminal/ or external terminal.

https://github.com/JunoLab/atom-julia-client/tree/master/lib/connection
https://github.com/JunoLab/atom-ink/tree/master/lib/console

**Comment by UziTech** [comment]
I don't know if that is possible since all x-terminal does is send text to the terminal process and display output from the terminal process. I'm guessing it would require a custom terminal process.

**Comment by aminya** [comment]
I updated the issue to be more exact. I guess this helps to go in the right way.

**Comment by UziTech** [comment]
I'm going to close this as it seems outside the scope of this project.
